const DEMO={"RA-P-7K4M9Q":{name:"Mario Rossi",state:"PROVA",trials:0},"RA-P-2F8X3N":{name:"Giulia Bianchi",state:"PROVA",trials:2},"RA-I-9T6C2V":{name:"Andrea Verdi",state:"ISCRITTO",trials:2}};
const app=document.querySelector('#app');
const params=new URLSearchParams(location.search); const view=params.get('view')||'home';
const get=id=>{const base=DEMO[id];if(!base)return null;const saved=JSON.parse(localStorage.getItem('ra-demo-'+id)||'null');return saved||base};
const save=(id,data)=>localStorage.setItem('ra-demo-'+id,JSON.stringify(data));
function shell(html){app.innerHTML=`<section class="card">${html}</section>`}
function home(){shell(`<div class="eyebrow">Prototipo operativo</div><h1>Presenze Romatletica</h1><p>Due flussi separati, un solo QR personale.</p><a class="button" href="?view=card&id=RA-P-7K4M9Q">Apri tessera famiglia</a><a class="button secondary" href="?view=scanner">Apri scanner prove</a><a class="button secondary" href="?view=card&id=RA-I-9T6C2V">Esempio iscritto</a><p class="notice">Questa anteprima usa esclusivamente nominativi dimostrativi.</p>`)}
function card(){const id=params.get('id')||'';const p=get(id);if(!p)return unknown();const active=p.state==='ISCRITTO';shell(`<div class="eyebrow">Tessera digitale</div><h1>${p.name}</h1><div class="status ${active?'green':p.trials>=2?'red':'orange'}">${active?'ISCRITTO':p.trials>=2?'PROVE GRATUITE TERMINATE':`PROVA ${p.trials+1} DI 2`}</div><div class="qr"><img alt="QR personale" src="https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=8&data=${encodeURIComponent(id)}"></div><div class="id">${id}</div>${!active&&p.trials>=2?`<a class="button" href="#" onclick="alert('Qui inseriremo il link Golee per l’iscrizione definitiva');return false">ISCRIVITI A ROMATLETICA</a>`:''}<p>Mostra questo QR all’ingresso del campo.</p>`)}
function scanner(){shell(`<div class="eyebrow">Ingresso campo · Prove</div><h1>Scansiona il QR</h1><video id="camera" playsinline></video><button id="start">ATTIVA FOTOCAMERA</button><label for="manual">Oppure inserisci il codice</label><input id="manual" placeholder="RA-P-…"><button class="secondary" id="lookup">CERCA</button><p class="notice">Se il telefono non supporta la lettura automatica, il codice sotto al QR resta sempre utilizzabile.</p>`);document.querySelector('#start').onclick=startCamera;document.querySelector('#lookup').onclick=()=>openPerson(document.querySelector('#manual').value.trim().toUpperCase())}
async function startCamera(){if(!('BarcodeDetector'in window)){alert('Su questo telefono usa il codice scritto sotto al QR.');return}try{const video=document.querySelector('#camera');video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});await video.play();const detector=new BarcodeDetector({formats:['qr_code']});const tick=async()=>{const codes=await detector.detect(video);if(codes[0]){video.srcObject.getTracks().forEach(t=>t.stop());openPerson(codes[0].rawValue);return}requestAnimationFrame(tick)};tick()}catch(e){alert('Fotocamera non disponibile. Inserisci il codice sotto al QR.') }}
function openPerson(id){const p=get(id);if(!p)return unknown();const active=p.state==='ISCRITTO';const ended=!active&&p.trials>=2;shell(`<div class="eyebrow">Verifica atleta</div><h1>${p.name}</h1><div class="status ${active?'green':ended?'red':'orange'}">${active?'ISCRITTO':ended?'PROVE GRATUITE TERMINATE':`PROVA ${p.trials+1} DI 2`}</div>${ended?'<p>Per continuare è necessario completare l’iscrizione.</p>':`<button id="register">${active?'REGISTRA PRESENZA':'REGISTRA PROVA'}</button>`}<a class="button secondary" href="?view=scanner">SCANSIONA UN ALTRO QR</a>`);const b=document.querySelector('#register');if(b)b.onclick=()=>register(id,p)}
function register(id,p){if(p.state==='PROVA')p.trials=Math.min(2,p.trials+1);save(id,p);shell(`<p class="success">✓</p><h1>${p.state==='PROVA'?'Prova registrata':'Presenza registrata'}</h1><div class="status green">${p.name}</div><a class="button" href="?view=scanner">SCANSIONA IL PROSSIMO</a>`)}
function unknown(){shell(`<div class="status red">QR NON RICONOSCIUTO</div><p>Controlla il codice e riprova.</p><a class="button" href="?view=scanner">TORNA ALLO SCANNER</a>`)}
({home,card,scanner}[view]||home)();
